spring:
  cloud:
    gateway:
      routes:
        #        - id: test_route
        #          uri: https://baidu.com
        #          predicates:
        #            - Query=url,baidu
        #
        #        - id: qq_route
        #          uri: https://qq.com
        #          predicates:
        #            - Query=url,qq

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: third-party-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/renren-fast/**
          filters:
            - RewritePath=/api/renren-fast/(?<segment>/?.*), /$\{segment}

        - id: yimuziy_product_route
          uri: lb://mall-product
          predicates:
            - Host=yimuziymall.com,item.yimuziymall.com

        - id: yimuziy_search_route
          uri: lb://mall-search
          predicates:
            - Host=search.yimuziymall.com

        - id: yimuziy_auth_route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.yimuziymall.com

        - id: yimuziy_cart_route
          uri: lb://mall-cart
          predicates:
            - Host=cart.yimuziymall.com

        - id: yimuziy_order_route
          uri: lb://mall-order
          predicates:
            - Host=order.yimuziymall.com




## 前端项目, /api
## http://localhost:88/api/product/category/list/tree
## http://localhost:10000/renren-fast/product/category/list/tree